### ISSUE TITLE
FEATUREREQUEST: Dynamic brevo attributes

### ISSUE THREAD

**Issue by chrisi51** [studiomitte/brevo#9]
Thanks for this Extension! =)

Would it be possible, to have a dynamic field list of brevo attributes? 
For the moment you have firstname, lastname, email and source hard coded.

Wouldn't it be better to have a list of attributes instead and the brevo finisher would ask for the corresponding form field for each given brevo attribute? 
I could imagine a single inputfield with a comma separeted list of custom brevo fields. 

Another (probably much easier) way would be to just add some more fields for custom attributes, which can be used or just be ignored if there is no need for. 

The usecase for that would be for example a gender/salutation field or any kind of product selection, for which you want to register.

Thanx 
Chris

**Comment by chrisi51** [comment]
Just found https://github.com/studiomitte/brevo/blob/d4c7b7292074ef18ce3e28a454e19f596dacfb6d/Resources/Private/Example/brevo-example.form.yaml#L18 ... so its already possible, but only able to be made in the form.yaml itself.

Was just missing it in the UI of the finisher. so its perfectly ok this way! =)

Probably worth some words in the README =)

**Comment by chesio** [comment]
I needed the ability to set additional attributes in Form Editor and ended up adding the following configuration, which works flawlessly. I used the configuration of `recipients` field in `EmailToReceiver` finisher as basis for my code as it is functionally identical (allows to populate an array option with custom key and value pairs):

```yaml
TYPO3:
  CMS:
    Form:
      prototypes:
        standard:
          formElementsDefinition:
            Form:
              formEditor:
                propertyCollections:
                  finishers:
                    1483353712:
                      editors:
                        1000:
                          identifier: additionalAttributes
                          templateName: Inspector-PropertyGridEditor
                          label: 'Zusätzliche Brevo Attribute'
                          propertyPath: options.additionalAttributes
                          propertyValidators:
                            10: NotEmpty
                          fieldExplanationText: 'Für jedes Attribut kann eine Feld-Referenz und/oder ein fixer Wert eingegeben werden.'
                          isSortable: true
                          enableAddRow: true
                          enableDeleteRow: true
                          useLabelAsFallbackValue: false
                          gridColumns:
                            -
                              name: value
                              title: Attribute
                            -
                              name: label
                              title: Feld/Wert

```

I can create proper PR with label references instead of hardcorded strings - just let me know if you find such code useful.
